# Generated by Django 3.2.14 on 2022-08-02 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jornada',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='programasacademico',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
